name: Postman API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run main collection (single iteration)
        run: |
          newman run collections/restful-booker-collection.json \
          -e environments/restful-booker-env.json \
          --folder "auth" \
          --folder "Health & Smoke Tests" \
          --folder "Booking - CRUD" \
          -r cli,htmlextra \
          --reporter-htmlextra-export reports/main-report.html
        continue-on-error: true

      - name: Run data-driven tests (5 iterations via CSV)
        run: |
          newman run collections/restful-booker-collection.json \
           -e environments/restful-booker-env.json \
           --folder "Data-Driven Tests" \
           -d data/booking-test-data.csv \
           -r cli,htmlextra \
           --reporter-htmlextra-export reports/data-driven-report.html
        continue-on-error: true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/*.html
         